# frozen_string_literal: true

source "https://rubygems.org"

gem "puppet-editor-services"

# # ruby used to provide these in stdlib but now they must be defined
gem "base64"
gem "syslog"
gem "ostruct"
gem "benchmark"
gem "racc"
gem "yard", '~> 0.9.28'
