source 'https://rubygems.org'

gem 'voxpupuli-puppet-lint-plugins'

# ruby used to provide these in stdlib but now they must be defined
gem 'base64'
gem 'benchmark'
gem 'ostruct'
gem 'racc'
gem 'syslog'
